# Site settings
title: WebConfs - A blog about web conferences
email: coolwebconfs@gmail.com
description: A blog about my favorite web conferences.
url: "http://webconfs.me" # the base hostname & protocol for your site
baseurl: "/jekyll_treehouse" # the subpath of your site, e.g. /blog/
twitter_username: YepItsSal
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Sally Gradle
      layout: "post"
      category: conferences
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"





